spring:
  main:
    banner-mode: "off"
vertx:
  worker-pool-size: 20
  verticle:
    deploy-timeout-ms: 5000
    instances: 1
http:
  port: 8080
http-client:
  max-pool-size: 32768
  connect-timeout-ms: 2500
external-url: http://localhost:8000
admin-port: 6060
default-timeout-ms: 250
max-request-size: 262144
adapters:
  rubicon:
    endpoint: http://exapi-us-east.rubiconproject.com/a/api/exchange.json
    usersync-url: https://pixel.rubiconproject.com/exchange/sync.php?p=prebid
  appnexus:
    endpoint: http://ib.adnxs.com/openrtb2
    usersync-url: "//ib.adnxs.com/getuid?"
  facebook:
    endpoint: https://an.facebook.com/placementbid.ortb
    nonSecureEndpoint: http://an.facebook.com/placementbid.ortb
  pulsepoint:
    endpoint: http://bid.contextweb.com/header/s/ortb/prebid-s2s
    usersync-url: "//bh.contextweb.com/rtset?pid=561205&ev=1&rurl="
  indexexchange:
    usersync-url: "//ssum-sec.casalemedia.com/usermatchredir?s=184932&cb=https%3A%2F%2Fprebid.adnxs.com%2Fpbs%2Fv1%2Fsetuid%3Fbidder%3DindexExchange%26uid%3D"
  lifestreet:
    endpoint: https://prebid.s2s.lfstmedia.com/adrequest
    usersync-url: "//ads.lfstmedia.com/idsync/137062?synced=1&ttl=1s&rurl="
  pubmatic:
    endpoint: http://openbid.pubmatic.com/translator?source=prebid-server
    usersync-url: "//ads.pubmatic.com/AdServer/js/user_sync.html?predirect="
  conversant:
    endpoint: http://media.msg.dotomi.com/s2s/header/24
    usersync-url: http://prebid-match.dotomi.com/prebid/match?rurl=
metrics:
  metricType: flushingCounter
datacache:
  cache-size: 10000
  ttl-seconds: 360
stored-requests:
  pool-size: 20
  in-memory-cache:
    cache-size: 10000
    ttl-seconds: 360
recaptcha-url: https://www.google.com/recaptcha/api/siteverify
recaptcha-secret: secret_value
host-cookie:
  opt-out-url: http://prebid.org/optout
  opt-in-url: http://prebid.org/optin
